name: Auto Fix & Format

on:
  push:
    branches:
      - main
  pull_request:  # optional, runs on PRs too

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # allow bot to commit changes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{html,css,js}
          commit_message: "Auto-format: Prettier"
